---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app bazarr
  namespace: media
spec:
  interval: 15m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: kah-common-chart
      version: 1.2.2
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 15m
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    global:
      nameOverride: *app
    image:
      repository: lscr.io/linuxserver/bazarr
      tag: 1.1.1
    env:
      TZ: "${TIMEZONE}"
      PUID: 1035
      PGID: 65537
    service:
      main:
        ports:
          http:
            port: 6767
    ingress:
      main:
        enabled: true
        ingressClassName: "traefik"
        annotations:
          cert-manager.io/cluster-issuer: "letsencrypt-production"
          hajimari.io/enable: "true"
          hajimari.io/icon: "subtitles"
        hosts:
          - host: &host "bazarr.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host
            secretName: bazarr-tls
    podSecurityContext:
      supplementalGroups:
        - 65537
    persistence:
      config:
        enabled: true
        existingClaim: bazarr-config-v1
      movies:
        enabled: true
        existingClaim: nfs-media-movies-pvc
        mountPath: /movies
      tv:
        enabled: true
        existingClaim: nfs-media-tv-pvc
        mountPath: /tv
      backup:
        enabled: true
        type: nfs
        server: ${NAS_ADDR}
        path: /volume2/Backups/apps/bazarr
        mountPath: /config/Backups
        readOnly: false
