---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: promtail
  namespace: monitoring
spec:
  interval: 15m
  chart:
    spec:
      # renovate: registryUrl=https://grafana.github.io/helm-charts
      chart: promtail
      version: 6.2.2
      sourceRef:
        kind: HelmRepository
        name: grafana-charts
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    image:
      registry: ghcr.io
      repository: k8s-at-home/promtail
      tag: 2.6.1
    config:
      clients:
        - url: http://loki.monitoring:3100/loki/api/v1/push
      snippets:
        extraScrapeConfigs: |
          # Add an additional scrape config for syslog
          - job_name: syslog
            syslog:
              listen_address: 0.0.0.0:{{ .Values.extraPorts.syslog.containerPort }}
              labels:
                job: syslog
            relabel_configs:
              - source_labels:
                  - __syslog_message_hostname
                target_label: hostname

              # example label values: kernel, CRON, kubelet
              - source_labels:
                  - __syslog_message_app_name
                target_label: app

              # example label values: debug, notice, informational, warning, error
              - source_labels:
                  - __syslog_message_severity
                target_label: level
          - job_name: journal
            journal:
              path: /var/log/journal
              max_age: 12h
              labels:
                job: systemd-journal
            relabel_configs:
              - source_labels:
                  - __journal__hostname
                target_label: hostname

              # example label values: kubelet.service, containerd.service
              - source_labels:
                  - __journal__systemd_unit
                target_label: unit

              # example label values: debug, notice, info, warning, error
              - source_labels:
                  - __journal_priority_keyword
                target_label: level
    extraVolumes:
      - name: journal
        hostPath:
          path: /var/log/journal
      - name: machine-id
        hostPath:
          path: /etc/machine-id

    extraVolumeMounts:
      - name: journal
        mountPath: /var/log/journal
        readOnly: true
      - name: machine-id
        mountPath: /etc/machine-id
        readOnly: true

    extraPorts:
      syslog:
        name: tcp-syslog
        containerPort: 1514
        service:
          type: LoadBalancer
          loadBalancerIP: "${METALLB_PROMTAIL_SYSLOG_IP}"
          port: 80
          externalTrafficPolicy: Local

    serviceMonitor:
      enabled: true

    resources:
      requests:
        cpu: 476m
        memory: 127M
      limits:
        cpu: 1380m
        memory: 654M
