---
creation_rules:
  - path_regex: provision/.*\.sops\.ya?ml
    unencrypted_regex: "^(kind)$"
    age: >-
      age1zlky9v29hdr6mpaqp7g4rz3m0mj8ttfey3h5prz4qa9la4ue9q0sn690tc
  - path_regex: cluster/.*\.ya?ml
    encrypted_regex: "^(data|stringData)$"
    age: >-
      age1zlky9v29hdr6mpaqp7g4rz3m0mj8ttfey3h5prz4qa9la4ue9q0sn690tc
