---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: jellyfin
  namespace: media
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: jellyfin
      version: 9.4.1
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
  values:
    image:
      repository: docker.io/jellyfin/jellyfin
      tag: 10.8.0-beta2
    env:
      TZ: "Europe/Warsaw"
      JELLYFIN_CACHE_DIR: "/config/cache"
    podSecurityContext:
      supplementalGroups:
        - 44
        - 109
        - 100
      fsGroup: 65537
    ingress:
      main:
        enabled: true
        ingressClassName: "traefik"
        annotations:
          cert-manager.io/cluster-issuer: "letsencrypt-production"
          hajimari.io/enable: "true"
          hajimari.io/icon: "filmstrip-box-multiple"
        hosts:
          - host: "jellyfin.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - "jellyfin.${SECRET_DOMAIN}"
            secretName: jellyfin-tls
    persistence:
      config:
        enabled: true
        existingClaim: jellyfin-config-v1
      tv:
        enabled: true
        existingClaim: nfs-media-tv-pvc
        mountPath: /tv
      movies:
        enabled: true
        existingClaim: nfs-media-movies-pvc
        mountPath: /movies
      transcode:
        enabled: true
        type: emptyDir
        medium: Memory
    resources:
      requests:
        gpu.intel.com/i915: 1
        cpu: 500m
        memory: 500Mi
      limits:
        gpu.intel.com/i915: 1
        memory: 4000Mi
