---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: home-assistant
  namespace: home
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: home-assistant
      version: 13.0.2
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: ghcr.io/home-assistant/home-assistant
      tag: 2022.4.5

    env:
      TZ: "Europe/Warsaw"
    envFrom:
      - secretRef:
          name: home-assistant

    ingress:
      main:
        enabled: true
        annotations:
          kubernetes.io/ingress.class: "nginx"
          hajimari.io/enable: "true"
          hajimari.io/icon: "home-assistant"
        hosts:
          - host: "hass.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - "hass.${SECRET_DOMAIN}"

    persistence:
      config:
        enabled: true
        existingClaim: home-assistant-config-v1

    postgresql:
      enabled: true
      postgresqlUsername: home-assistant
      postgresqlPassword: ${HOME_ASSISTANT_POSTGRES_PASS}"
      postgresqlDatabase: home-assistant
      persistence:
        enabled: true

    influxdb:
      enabled: true
      architecture: standalone
      database: home_assistant
      authEnabled: false
      persistence:
        enabled: true

    metrics:
      enabled: true
      serviceMonitor:
        interval: 1m
        scrapeTimeout: 30s
        ## See https://www.home-assistant.io/docs/authentication/ for where to find
        ## long lived access token creation under your account profile, which is
        ## needed to monitor Home Assistant
        bearerTokenSecret:
          name: "home-assistant"
          key: "PROMETHEUS_TOKEN"
      prometheusRule:
        enabled: true
        rules:
          - alert: HomeAssistantAbsent
            annotations:
              description: Home Assistant has disappeared from Prometheus service discovery.
              summary: Home Assistant is down.
            expr: |
              absent(up{job=~".*home-assistant.*"} == 1)
            for: 5m
            labels:
              severity: critical

    addons:
      codeserver:
        enabled: true
        image:
          repository: ghcr.io/k8s-at-home/code-server
          tag: v4.3.0
        workingDir: "/config"
        args:
          - --auth
          - "none"
          - --user-data-dir
          - "/config/.vscode"
          - --extensions-dir
          - "/config/.vscode"
        ingress:
          enabled: true
          annotations:
            kubernetes.io/ingress.class: "nginx"
            hajimari.io/enable: "true"
            hajimari.io/icon: "home-assistant"
          hosts:
            - host: "hass-config.${SECRET_DOMAIN}"
              paths:
                - path: /
                  pathType: Prefix
          tls:
            - hosts:
                - "hass-config.${SECRET_DOMAIN}"
        volumeMounts:
          - name: config
            mountPath: /config
