---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: home-assistant
  namespace: home
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: home-assistant
      version: 10.1.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: ghcr.io/home-assistant/home-assistant
      tag: 2021.9.5
    env:
      TZ: "Europe/Warsaw"
    envFrom:
      - secretRef:
          name: home-assistant
    ingress:
      main:
        enabled: true
        annotations:
          kubernetes.io/ingress.class: "nginx"
          hajimari.io/enable: "true"
        hosts:
          - host: "hass.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - "hass.${SECRET_DOMAIN}"
    prometheus:
      serviceMonitor:
        enabled: true
    persistence:
      config:
        enabled: true
        existingClaim: home-assistant-config-v1
    postgresql:
      enabled: true
      postgresqlUsername: home-assistant
      postgresqlPassword: ${HOME_ASSISTANT_POSTGRES_PASS}"
      postgresqlDatabase: home-assistant
      persistence:
        enabled: true
    influxdb:
      enabled: true
      architecture: standalone
      database: home_assistant
      authEnabled: false
      persistence:
        enabled: true
    addons:
      codeserver:
        enabled: true
        image:
          repository: ghcr.io/k8s-at-home/code-server
          tag: 3.11.1
        workingDir: "/config"
        args:
          - --auth
          - "none"
          - --user-data-dir
          - "/config/.vscode"
          - --extensions-dir
          - "/config/.vscode"
        ingress:
          enabled: true
          annotations:
            kubernetes.io/ingress.class: "nginx"
          hosts:
            - host: "hass-config.${SECRET_DOMAIN}"
              paths:
                - path: /
                  pathType: Prefix
          tls:
            - hosts:
                - "hass-config.${SECRET_DOMAIN}"
        volumeMounts:
          - name: config
            mountPath: /config
