apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - bitnami-charts.yaml
  - ingress-nginx-charts.yaml
  - jetstack-charts.yaml
  - k8s-at-home-charts.yaml
  - metallb-charts.yaml
  - nfs-provisioner-charts.yaml
  - prometheus-community-charts.yaml
  - stakater-charts.yaml
  - weaveworks-kured-charts.yaml
  - kubernetes-sigs-descheduler-charts.yaml
  - longhorn-charts.yaml
  - vernemq-charts.yaml
  - infracloudio-charts.yaml
  - grafana-charts.yaml
  - deliveryhero-charts.yaml
  - metrics-server-charts.yaml
