---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: node-problem-detector
  namespace: kube-system
spec:
  interval: 15m
  chart:
    spec:
      # renovate: registryUrl=https://charts.deliveryhero.io/
      chart: node-problem-detector
      version: 2.2.5
      sourceRef:
        kind: HelmRepository
        name: deliveryhero-charts
        namespace: flux-system
      interval: 15m
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    image:
      repository: "k8s.gcr.io/node-problem-detector/node-problem-detector"
      tag: "v0.8.10"
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
                - key: kubernetes.io/arch
                  operator: In
                  values:
                    - amd64
    resources:
      limits:
        cpu: 10m
        memory: 80Mi
      requests:
        cpu: 10m
        memory: 80Mi
