---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: blocky
  namespace: networking
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: blocky
      version: 9.1.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: ghcr.io/0xerr0r/blocky
      tag: v0.17

    controller:
      replicas: 2
      strategy: RollingUpdate

    env:
      TZ: "Europe/Warsaw"

    service:
      main:
        ports:
          http:
            port: 4000
      dns-tcp:
        enabled: true
        type: LoadBalancer
        loadBalancerIP: 10.0.60.111
        ports:
          dns-tcp:
            enabled: true
            port: 53
            protocol: TCP
            targetPort: 53
        externalTrafficPolicy: Local
        annotations:
          metallb.universe.tf/allow-shared-ip: blocky
      dns-udp:
        enabled: true
        type: LoadBalancer
        loadBalancerIP: 10.0.60.111
        ports:
          dns-udp:
            enabled: true
            port: 53
            protocol: UDP
            targetPort: 53
        externalTrafficPolicy: Local
        annotations:
          metallb.universe.tf/allow-shared-ip: blocky

    metrics:
      enabled: true
      serviceMonitor:
        interval: 30s
        scrapeTimeout: 10s
      prometheusRule:
        enabled: true
        rules:
          - alert: BlockyDisabled
            annotations:
              description: Blocky's ad blocking has been disabled for 15min.
                Please re-enable protection.
              summary: Blocky is disabled.
            expr: |
              blocky_blocking_enabled == 0
            for: 15m
            labels:
              severity: critical

    resources:
      requests:
        memory: 280Mi
        cpu: 50m
      limits:
        memory: 1000Mi

    config: |
      upstream:
        externalResolvers:
        - tcp+udp:8.8.8.8
        - tcp+udp:8.8.4.4
        - tcp+udp:1.1.1.1
        - tcp-tls:1.0.0.1:853
        - https://cloudflare-dns.com/dns-query
      customDNS:
        mapping:
          ${SECRET_DOMAIN}: 10.0.60.100
          plex.${SECRET_DOMAIN}: 10.0.10.13
          dsm.${SECRET_DOMAIN}: 10.0.10.13
          minio.${SECRET_DOMAIN}: 10.0.10.13
          omada.${SECRET_DOMAIN}: 10.0.10.13
      blocking:
        blackLists:
          ads:
          - https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts
          - https://s3.amazonaws.com/lists.disconnect.me/simple_ad.txt
          - http://sysctl.org/cameleon/hosts
          - https://s3.amazonaws.com/lists.disconnect.me/simple_tracking.txt
          - https://raw.githubusercontent.com/PolishFiltersTeam/KADhosts/master/KADhosts.txt
          - https://v.firebog.net/hosts/AdguardDNS.txt
          kids:
          - https://raw.githubusercontent.com/StevenBlack/hosts/master/alternates/fakenews-gambling-porn/hosts
          none:
        whiteLists:
          ads:
          - https://raw.githubusercontent.com/anudeepND/whitelist/master/domains/whitelist.txt
        clientGroupsBlock:
          default:
            - ads
      clientLookup:
        upstream: tcp+udp:10.0.60.1
      prometheus:
        enable: true
        path: /metrics
      httpPort: 4000
      logLevel: info
      bootstrapDns: tcp:1.1.1.1
