---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: paperless
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: paperless
      version: 8.8.2
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
  values:
    image:
      repository: ghcr.io/paperless-ngx/paperless-ngx
      tag: 1.7.1
      pullPolicy: IfNotPresent
    env:
      PAPERLESS_OCR_LANGUAGE: "eng"
      PAPERLESS_TIME_ZONE: "Europe/Warsaw"
      PAPERLESS_URL: "https://docs.${SECRET_DOMAIN}"
    ingress:
      main:
        enabled: true
        ingressClassName: "traefik"
        annotations:
          cert-manager.io/cluster-issuer: "letsencrypt-production"
          hajimari.io/enable: "true"
          hajimari.io/icon: "file-pdf-box"
        hosts:
          - host: "docs.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - "docs.${SECRET_DOMAIN}"
            secretName: docs-tls
    podSecurityContext:
      fsGroup: 65541
    persistence:
      data:
        enabled: true
        existingClaim: paperless-data
      media:
        enabled: true
        type: custom
        volumeSpec:
          nfs:
            server: ${NAS_ADDR}
            path: /volume2/documents/media
      consume:
        enabled: true
        type: custom
        volumeSpec:
          nfs:
            server: ${NAS_ADDR}
            path: /volume2/documents/consume
      export:
        enabled: true
        type: custom
        volumeSpec:
          nfs:
            server: ${NAS_ADDR}
            path: /volume2/documents/export
    redis:
      enabled: true
