---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: paperless
  namespace: default
spec:
  interval: 15m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: paperless
      version: 9.1.3
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 15m
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    image:
      repository: ghcr.io/paperless-ngx/paperless-ngx
      tag: 1.10.0
    env:
      PAPERLESS_OCR_LANGUAGE: "pol+eng"
      PAPERLESS_OCR_LANGUAGES: "pol"
      PAPERLESS_TIME_ZONE: "${TIMEZONE}"
      PAPERLESS_URL: "https://docs.${SECRET_DOMAIN}"
      PAPERLESS_REDIS: redis://paperless-redis-master:6379
      USERMAP_UID: 1042
      USERMAP_GID: 65541
    ingress:
      main:
        enabled: true
        ingressClassName: "traefik"
        annotations:
          cert-manager.io/cluster-issuer: "letsencrypt-production"
          hajimari.io/enable: "true"
          hajimari.io/icon: "file-pdf-box"
        hosts:
          - host: &host "docs.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host
            secretName: docs-tls
    podSecurityContext:
      fsGroup: 65541
    persistence:
      data:
        enabled: true
        existingClaim: paperless-data
      media:
        enabled: true
        type: custom
        volumeSpec:
          nfs:
            server: ${NAS_ADDR}
            path: /volume2/documents/media
      consume:
        enabled: true
        type: custom
        volumeSpec:
          nfs:
            server: ${NAS_ADDR}
            path: /volume2/documents/consume
      export:
        enabled: true
        type: custom
        volumeSpec:
          nfs:
            server: ${NAS_ADDR}
            path: /volume2/documents/export
    redis:
      enabled: true
    postgresql:
      enabled: true
      postgresqlPassword: ${PAPERLESS_POSTGRES_PASSWORD}
      persistence:
        enabled: true
