# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:mroc7nB8Bg==,iv:lgNOsff2LirgDemEixTzkGMLgX+dbWqdbu/P7Y3qJnM=,tag:bFpAGe3aHmDetj0a6PF/sg==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:dGjE8hTgBHPfA+8oa8jhZpN1,iv:88gwsSzbCYxI5eno6dkKaKOd+skC5rIu8QMLDt2yiRk=,tag:ry7bkcwmFD5HMJzpr6g6rA==,type:str]
    HOME_ASSISTANT_POSTGRES_PASS: ENC[AES256_GCM,data:EcJKgZQ/x5Hn0FwPindZKw==,iv:HKVZc5ybQJdGa0eNCEK3HZqV/kRCkWq/ukCaoIPEnpQ=,tag:KZgKpazmq9z4S1MNre48nA==,type:str]
    VPN_PORT: ENC[AES256_GCM,data:x05bfQ==,iv:t3OtVi8D6tq0tXcgqjcLft+T4pgna5d7BTEjvRKbiKo=,tag:WXE+zGCSySvZzmKOuHlpTw==,type:str]
    VPN_FORWARDED_PORT_1: ENC[AES256_GCM,data:LRUTtuY=,iv:NunKO8m16nJl/p5Tz7zFL1IqqtBfU/cHUzJtVcvMOVI=,tag:sOZ3sGVSgMsOBKVhSaO/Rw==,type:str]
    VPN_COUNTRY: ENC[AES256_GCM,data:gh4=,iv:eyrsLXHzoV/6UCBfxJxxP8HrvlvWkAAqR7qbYCpsegE=,tag:0MxJHwe6ydoQv2Mm+ItXtw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-08-23T08:41:44Z"
    mac: ENC[AES256_GCM,data:JjvoLrWyBovkZSwj39lwBSIvb1eWAkXbCyVoYLYmRyH6z4jLqW3lwVOAXANnspk+SW22IB5djZZDkQyvwpLmCOUsMsnTHmR7zoOvOwpS0mES69dsNY3W3IZ12pQSJlOGH4wsfWPGMxbkYSRsFTH3oTitKlzamUiTAKlh7GGn+0c=,iv:7W5sGFZ5nEbuQnOTLtPqatvmFUj6uoC63tpThk/O16o=,tag:Ee34gX0wJRI8gNw+g2p9eg==,type:str]
    pgp:
        - created_at: "2021-08-18T10:58:47Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA7t8C5PioujHAQ/5AX09sKHM7jTJxOVDpQH9NRK4hTXSiU+NmNlFLaVg1h8g
            1Y1bmn2SMCGOwzWOun0H9aViboFDqxl6qyahBpNsLlvlKBeNtclb5ojDVz+41038
            pV1pIyCa6GMTXtHGlaJCG32UUf5by41eLQr8VrquESiHAUJGvrzA/ZEQ24UCuGj+
            +ZOR3dVeqj9zqtuaZ54kL9nDF574sjL99fWN8AEI6XGMULwj458ZQM56Ha+BbKLs
            Q9T45BIEXV6GGqunLcAGhVoQ5xoAA0ZlRZ7CQiLLdZPOggNLtpYx+lcR33FwVFEY
            zCzJ69yk33UT7Ki7bqCFbUBybM9ggKZgd+KY4TIIYXSUWre9OFkvZI6e+jvf3G8t
            jwBZEs/g8nIao/kuvoUfSqkm3KEDaEiIwflW/cMUnZIsZNOR32vG6b4GHHjK/axL
            e+Jbz5Hxw3qHQ/JA86mLSdAma6iBgNt//h7jxHEFR+VbMT0OhERatRCXCA3STduW
            /KnHb+4Spzk4ghwSAUAG2SchpbzXBvXEb0bIy3OMrwqDQzOOhyVsCi4lbsQtglNE
            9oa8LBKjVowJScPM3XMk5Ab51kZIv8Xo3TaWWv9P2fYWq1o94oVjAijF/0cBJHlE
            ATr832RMaPb5TRD+YMl6796z2lggAWvyRIVF8zUF7Ohoz+4lNAoUvohXpjB5s73S
            XgGK9RzHRYPkL57vkWRwkYa1DHiRsUhP5aexiTJWBShQz41NGJha+/yRG04Bl3cJ
            8P4u3omKa4BvmMgda5gV3mlyagBOtk2g8pypRcsTmRDcEeWiSpWO4vjeyszu5Mc=
            =rb/0
            -----END PGP MESSAGE-----
          fp: 56A41467DC315614D8B72CF044DD4CDA78ADB2FC
        - created_at: "2021-08-18T10:58:47Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA8QwD8uzV5FYARAApqHTa+stxPy38yzLHaAYmdpWfmUi+4torIwY6W4ZjGax
            cgDGfOpbTBBQ8DDNFHetYtOeCJE3z4due9Ga8J1M0sDv+AeeO1dDNthz4cw+gHIt
            16DqmwwU/ZtPrRdeAAxLnyAOV6V/Q1PUsS/u/1t/xEcOxMFQZe18SjgDk8eSS/YN
            BEzm2ANoQkHyM6daeujfVZTqZUgwn0lT/zNNKKVFFtWPJ3sJbLljYgCDOC2f4xRp
            wT7tV7gGB+F+QfS0MH2Sozvy1IkDWr5lgoh3f3vPQPd4o7LRcy7ivJQl8giq/2NL
            401Ipk1wFj29atqEA6EcdXN1bzuhIe4SUEcDq3BW9Kz/ZYYAp5fOk6/uOtaafwa/
            UFA1y2KfVhKoBg4TUtNr0z8GXw5u3B4Q6ZIRvsZctCir1S0mv9AW+NgtROdLvXGN
            rXu5jSXf4fy1rPyJ9DrgmpDmWiWZTYQpPPw1Fl4E8AzbIaI/HLnX2Ct5fCy/8Ja9
            xeuQny1WWRYMspnhK+k4FwOLksZGrWE6S4i5qAQBUiL/6Nugu32oiT+WgtI8/OBm
            5mtK0tbjnf6mF0sS+RkHW6RPbL5/ry7k+HwW8wnnb1SoMHLF5IeXofCaeQ888m7V
            gqivqLGYD70pN6LHZdBaddH7bkL5hE4XgwzeXt7QPdRiRdx+/RA/IgkBkdIpOczS
            XgEvvz0mosoo5HTsjeNWd0lYieSKqhm1WCWtuVRnIR9I4wVakshlwfPO/zJD/vbJ
            8pxs66TpAbMomPths74qRallLcGJHnG7tttb2e1HwoVYS3IzIUsRBrHEp/mTjBk=
            =9Gjj
            -----END PGP MESSAGE-----
          fp: 13A6D5C248F37AD97136AF8CA85CB335AA558F0F
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
