# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:mroc7nB8Bg==,iv:lgNOsff2LirgDemEixTzkGMLgX+dbWqdbu/P7Y3qJnM=,tag:bFpAGe3aHmDetj0a6PF/sg==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:dGjE8hTgBHPfA+8oa8jhZpN1,iv:88gwsSzbCYxI5eno6dkKaKOd+skC5rIu8QMLDt2yiRk=,tag:ry7bkcwmFD5HMJzpr6g6rA==,type:str]
    HOME_ASSISTANT_POSTGRES_PASS: ENC[AES256_GCM,data:EcJKgZQ/x5Hn0FwPindZKw==,iv:HKVZc5ybQJdGa0eNCEK3HZqV/kRCkWq/ukCaoIPEnpQ=,tag:KZgKpazmq9z4S1MNre48nA==,type:str]
    VPN_PORT: ENC[AES256_GCM,data:KXWWEzA=,iv:EavJlWA97GIgepcRTqd6OJOVumTnaYaoi7NBW3ifw2s=,tag:xUOQ+Bm4GYXoynpLtRdf/g==,type:str]
    VPN_FORWARDED_PORT_1: ENC[AES256_GCM,data:7I8j1Vw=,iv:eWhctWlxdtDS2G4j4VrfWZQDBp/GgQQTVpHfRi6aAJc=,tag:x6h7CmhY8oekOm3yk0C1Uw==,type:str]
    VPN_COUNTRY: ENC[AES256_GCM,data:gh4=,iv:eyrsLXHzoV/6UCBfxJxxP8HrvlvWkAAqR7qbYCpsegE=,tag:0MxJHwe6ydoQv2Mm+ItXtw==,type:str]
    CAM_FRONT_PASS: ENC[AES256_GCM,data:CA+wKYG0cFU=,iv:x4bhIVKDwuw7RJIP5BiGdbZdKWif/ZSTcGHgrs2RaMg=,tag:QufdrrOKdu3o8D++a7HMow==,type:str]
    CAM_BACK_PASS: ENC[AES256_GCM,data:UMDXibxqmCo=,iv:odnL+pPwhyF7V+5y0Ychf22x4stNDYtkmqhicGfT7cQ=,tag:sIR+G/DXeAUGoPG4A3XsNg==,type:str]
    SECRET_GRAFANA_PASSWORD: ENC[AES256_GCM,data:iQD9AchswPSGUINeRQSkCQ==,iv:utvAySd4XBbtP2hgKEuK+fZR7lzr4fns1V7w8sBf+dM=,tag:ny4WtMC8ix14odrpbVZlxg==,type:str]
    NAS_ADDR: ENC[AES256_GCM,data:LelXWqtXFKrAzg==,iv:STLxn2BIZZb9nXXo594Mt+foV8XFg3lMgVNZ1iltoB4=,tag:P9hBGrsCuY9Y3Q2SfWvO8Q==,type:str]
    SECRET_ALERT_MANAGER_DISCORD_WEBHOOK: ENC[AES256_GCM,data:5IkODTqoeWRVLc6oCBeInHTrTeXkndrGNjDQqUVfjAfUBXQ9m6dX5MSfQsZfR+9gIHtklYOxABUQG58u4no24Gd5Kt6KSCwtcaRxgNyQ3Kp434LUJ+9SSHzIaI872iwTh7r3p95pblilZKEzaA5nRJ64+kHbXcAP,iv:xEiuTqPB8KrGi19pbqSWrltT/iU/ja5bcAC27qsRdKM=,tag:BUQ6z2rPV9WV7bD3+R2LsQ==,type:str]
    SECRET_KURED_NOTIFY_URL: ENC[AES256_GCM,data:WfarTAnk4ZyuX25uM5cL6uFQW7XsJEXLMtJRW+iWvRou70NZrhAwXIZNdlxxpY/ygg4xM2aPnxPkME280Hy3nm8SNIffgokuyDG9QImz24Z/Vw==,iv:wwd7brBBYQQAZOb/Lb7JmHENCaaj0/ol2QQTiuNOqTY=,tag:p7IsFOi6PxUzRc7t7tDZmA==,type:str]
    SECRET_QB_USERNAME: ENC[AES256_GCM,data:hxA0sM0=,iv:mAIXMLB6+pvxafmZAiUmGv8rXMK4fVIi2Qum1tNd0kY=,tag:8ZG3xTlpkIv4yaHqXaeqog==,type:str]
    SECRET_QB_PASSWORD: ENC[AES256_GCM,data:wo6f7I8h44PF0w==,iv:7UI4BhknQMvBURhBjnYSkMovOQnRhp2pPi5QbR7vGOA=,tag:1tQcqqNND4xWk9qrDqc4sg==,type:str]
    LOKI_MINIO_ACCESS_KEY: ENC[AES256_GCM,data:qTvjvA==,iv:VNwyGkDgk70ZjtDyrLGMSfUBRfy/s2RcA4ZMwejDfio=,tag:zCJsphXYhE1dJ6ilbRQKrA==,type:str]
    LOKI_MINIO_SECRET_KEY: ENC[AES256_GCM,data:Y173rVxcK6duAE79LGLvog==,iv:U2Rhrrn05j4LL2Myv/VlyK6rCbfw2Mgc+3fK7Ji89LM=,tag:iD6Gg3DQPulCmuRbYrEKkg==,type:str]
    MIKROTIK_RB4011_IP: ENC[AES256_GCM,data:KAhaZ/B0+vIz,iv:Q+Xfbwv1jF/sMT5VBeFND24w+i8+9XAuGoExUx69wVE=,tag:YZrhdBJI7ItDw0o91iA8pQ==,type:str]
    MIKROTIK_RB4011_PASSWORD: ENC[AES256_GCM,data:7v98OqfqWJGJpA==,iv:5juByV7vtzz/cg90BM56mnT9X8Dzf13O8ybJKkvc5Io=,tag:p0dLDetLZ1fpvJB78CijMA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-04-07T06:43:39Z"
    mac: ENC[AES256_GCM,data:XJBHc6eZdzIobiI7TVSp9Hrc0tFr29N8qrOJ+FliQeCDvDLNyCdl57/Qab7zfarRsov8XBS6lXSZqBRuyME9+jtMx6NCRMTaTIoBTffVHW6DGAD+bCXRJMFn83jxW131Bvz/JDZkyVcgQ8dND9GlDvr95qqpXJdOnOVGC5+20ys=,iv:XThwBPUgdpX9lXJKIW66zdYooIkqCykQbqjFbNw9iZ4=,tag:05mOylFQ48+b72aaVn9Zog==,type:str]
    pgp:
        - created_at: "2021-08-18T10:58:47Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA7t8C5PioujHAQ/5AX09sKHM7jTJxOVDpQH9NRK4hTXSiU+NmNlFLaVg1h8g
            1Y1bmn2SMCGOwzWOun0H9aViboFDqxl6qyahBpNsLlvlKBeNtclb5ojDVz+41038
            pV1pIyCa6GMTXtHGlaJCG32UUf5by41eLQr8VrquESiHAUJGvrzA/ZEQ24UCuGj+
            +ZOR3dVeqj9zqtuaZ54kL9nDF574sjL99fWN8AEI6XGMULwj458ZQM56Ha+BbKLs
            Q9T45BIEXV6GGqunLcAGhVoQ5xoAA0ZlRZ7CQiLLdZPOggNLtpYx+lcR33FwVFEY
            zCzJ69yk33UT7Ki7bqCFbUBybM9ggKZgd+KY4TIIYXSUWre9OFkvZI6e+jvf3G8t
            jwBZEs/g8nIao/kuvoUfSqkm3KEDaEiIwflW/cMUnZIsZNOR32vG6b4GHHjK/axL
            e+Jbz5Hxw3qHQ/JA86mLSdAma6iBgNt//h7jxHEFR+VbMT0OhERatRCXCA3STduW
            /KnHb+4Spzk4ghwSAUAG2SchpbzXBvXEb0bIy3OMrwqDQzOOhyVsCi4lbsQtglNE
            9oa8LBKjVowJScPM3XMk5Ab51kZIv8Xo3TaWWv9P2fYWq1o94oVjAijF/0cBJHlE
            ATr832RMaPb5TRD+YMl6796z2lggAWvyRIVF8zUF7Ohoz+4lNAoUvohXpjB5s73S
            XgGK9RzHRYPkL57vkWRwkYa1DHiRsUhP5aexiTJWBShQz41NGJha+/yRG04Bl3cJ
            8P4u3omKa4BvmMgda5gV3mlyagBOtk2g8pypRcsTmRDcEeWiSpWO4vjeyszu5Mc=
            =rb/0
            -----END PGP MESSAGE-----
          fp: 56A41467DC315614D8B72CF044DD4CDA78ADB2FC
        - created_at: "2021-08-18T10:58:47Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA8QwD8uzV5FYARAApqHTa+stxPy38yzLHaAYmdpWfmUi+4torIwY6W4ZjGax
            cgDGfOpbTBBQ8DDNFHetYtOeCJE3z4due9Ga8J1M0sDv+AeeO1dDNthz4cw+gHIt
            16DqmwwU/ZtPrRdeAAxLnyAOV6V/Q1PUsS/u/1t/xEcOxMFQZe18SjgDk8eSS/YN
            BEzm2ANoQkHyM6daeujfVZTqZUgwn0lT/zNNKKVFFtWPJ3sJbLljYgCDOC2f4xRp
            wT7tV7gGB+F+QfS0MH2Sozvy1IkDWr5lgoh3f3vPQPd4o7LRcy7ivJQl8giq/2NL
            401Ipk1wFj29atqEA6EcdXN1bzuhIe4SUEcDq3BW9Kz/ZYYAp5fOk6/uOtaafwa/
            UFA1y2KfVhKoBg4TUtNr0z8GXw5u3B4Q6ZIRvsZctCir1S0mv9AW+NgtROdLvXGN
            rXu5jSXf4fy1rPyJ9DrgmpDmWiWZTYQpPPw1Fl4E8AzbIaI/HLnX2Ct5fCy/8Ja9
            xeuQny1WWRYMspnhK+k4FwOLksZGrWE6S4i5qAQBUiL/6Nugu32oiT+WgtI8/OBm
            5mtK0tbjnf6mF0sS+RkHW6RPbL5/ry7k+HwW8wnnb1SoMHLF5IeXofCaeQ888m7V
            gqivqLGYD70pN6LHZdBaddH7bkL5hE4XgwzeXt7QPdRiRdx+/RA/IgkBkdIpOczS
            XgEvvz0mosoo5HTsjeNWd0lYieSKqhm1WCWtuVRnIR9I4wVakshlwfPO/zJD/vbJ
            8pxs66TpAbMomPths74qRallLcGJHnG7tttb2e1HwoVYS3IzIUsRBrHEp/mTjBk=
            =9Gjj
            -----END PGP MESSAGE-----
          fp: 13A6D5C248F37AD97136AF8CA85CB335AA558F0F
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
