---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: qbittorrent
  namespace: media
spec:
  dependsOn:
    - name: vpn-gateway
      namespace: vpn-gateway
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: qbittorrent
      version: 13.2.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: ghcr.io/k8s-at-home/qbittorrent
      tag: v4.4.2
    env:
      TZ: "Europe/Warsaw"
    hostname: torrent
    ingress:
      main:
        enabled: true
        annotations:
          kubernetes.io/ingress.class: "nginx"
        hosts:
          - host: "qbittorrent.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - "qbittorrent.${SECRET_DOMAIN}"
    podSecurityContext:
      fsGroup: 65537
    persistence:
      config:
        enabled: true
        existingClaim: qbittorrent-config-v1
      downloads:
        enabled: true
        existingClaim: nfs-media-downloads-pvc
        mountPath: /downloads
    metrics:
      enabled: true
      serviceMonitor:
        interval: 30s
        scrapeTimeout: 5s
      prometheusRule:
        enabled: true
        rules:
          - alert: qBittorrentDown
            annotations:
              description: qBittorrent service is down.
              summary: qBittorrent is down.
            expr: |
              qbittorrent_up == 0
            for: 5m
            labels:
              severity: critical
      exporter:
        image:
          repository: esanchezm/prometheus-qbittorrent-exporter
          tag: v1.2.0
          pullPolicy: IfNotPresent
        env:
          user: "${SECRET_QB_USERNAME}"
          password: "${SECRET_QB_PASSWORD}"
