---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: sonarr
  namespace: media
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: sonarr
      version: 16.0.1
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: ghcr.io/k8s-at-home/sonarr
      tag: v3.0.7.1477
    env:
      TZ: "Europe/Warsaw"
    ingress:
      main:
        enabled: true
        annotations:
          kubernetes.io/ingress.class: "nginx"
        hosts:
          - host: "sonarr.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - "sonarr.${SECRET_DOMAIN}"
    podSecurityContext:
      fsGroup: 65537
    persistence:
      config:
        enabled: true
        existingClaim: sonarr-config-v1
      tv:
        enabled: true
        existingClaim: nfs-media-tv-pvc
        mountPath: /tv
      downloads:
        enabled: true
        existingClaim: nfs-media-downloads-pvc
        mountPath: /downloads
    metrics:
      enabled: true
      serviceMonitor:
        interval: 5m
        scrapeTimeout: 1m
      prometheusRule:
        enabled: true
        rules:
          - alert: SonarrDown
            annotations:
              description: Sonarr service is down.
              summary: Sonarr is down.
            expr: |
              sonarr_system_status == 0
            for: 5m
            labels:
              severity: critical
      exporter:
        image:
          repository: ghcr.io/onedr0p/exportarr
          tag: v1.0.0
        env:
          # -- metrics port
          port: 9794
          # -- Set to true to enable gathering of additional metrics (slow)
          additionalMetrics: false
          # -- Set to true to enable gathering unknown queue items
          unknownQueueItems: false
