---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app sonarr
  namespace: media
spec:
  interval: 15m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: kah-common-chart
      version: 1.2.2
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 15m
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    global:
      nameOverride: *app
    image:
      repository: ghcr.io/k8s-at-home/sonarr
      tag: v3.0.9.1549
    env:
      TZ: "${TIMEZONE}"
      SONARR__INSTANCE_NAME: Sonarr
      SONARR__APPLICATION_URL: "https://{{ .Release.Name }}.${SECRET_DOMAIN}"
      SONARR__LOG_LEVEL: info
      PUSHOVER_DEBUG: "false"
      PUSHOVER_APP_URL: &host "{{ .Release.Name }}.${SECRET_DOMAIN}"
    service:
      main:
        ports:
          http:
            port: 8989
    ingress:
      main:
        enabled: true
        ingressClassName: "traefik"
        annotations:
          cert-manager.io/cluster-issuer: "letsencrypt-production"
          hajimari.io/enable: "true"
          hajimari.io/icon: "television-classic"
        hosts:
          - host: *host
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host
            secretName: sonarr-tls
    podSecurityContext:
      supplementalGroups:
        - 65537
    persistence:
      config:
        enabled: true
        existingClaim: sonarr-config-v1
      tv:
        enabled: true
        existingClaim: nfs-media-tv-pvc
        mountPath: /tv
      downloads:
        enabled: true
        existingClaim: nfs-media-downloads-pvc
        mountPath: /downloads
      backup:
        enabled: true
        type: nfs
        server: ${NAS_ADDR}
        path: /volume2/Backups/apps/sonarr
        mountPath: /config/Backups
        readOnly: false
    resources:
      requests:
        cpu: 10m
        memory: 250Mi
      limits:
        memory: 2000Mi
