---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: frigate
  namespace: home
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: frigate
      version: 6.0.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: ghcr.io/k8s-at-home/frigate
      tag: 0.8.4-amd64
    ingress:
      main:
        enabled: true
        annotations:
          kubernetes.io/ingress.class: "nginx"
        hosts:
          - host: "frigate.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - "frigate.${SECRET_DOMAIN}"
    securityContext:
      privileged: true
    podSecurityContext:
      fsGroup: 65539
    persistence:
      data:
        enabled: true
        existingClaim: frigate-config-v1
        mountPath: /data
      media:
        enabled: true
        type: custom
        volumeSpec:
          nfs:
            server: 10.0.10.13
            path: /volume3/frigate
        mountPath: /media
      usb:
        enabled: true
        type: hostPath
        hostPath: /dev/bus/usb
      cache:
        enabled: true
        type: emptyDir
        medium: Memory
        sizeLimit: 2Gi
        mountPath: /dev/shm
    config: |
      mqtt:
        host: vernemq
        topic_prefix: frigate
        user: nouser
        password: nopassword
      database:
        path: /data/frigate.db
      detectors:
        coral:
          type: edgetpu
          device: usb
      objects:
        track:
        - person
        - dog
        - cat
        filters:
          person:
            min_area: 2500
            max_area: 100000
            threshold: 0.7
          dog:
            min_area: 1000
            max_area: 10000
            threshold: 0.7
          cat:
            min_area: 1000
            max_area: 10000
            threshold: 0.7
      ffmpeg:
        hwaccel_args:
        - -hwaccel
        - vaapi
        - -hwaccel_device
        - /dev/dri/renderD128
        - -hwaccel_output_format
        - yuv420p
      cameras:
        # --
        front:
          ffmpeg:
            inputs:
            - path: rtsp://admin:${CAM_FRONT_PASS}@10.0.40.10:554/h264Preview_01_sub
              roles:
              - detect
            - path: rtsp://admin:${CAM_FRONT_PASS}@10.0.40.10:554/h264Preview_01_main
              roles:
              - clips
              - record
              - rtmp
          height: 480
          width: 640
          fps: 7
          objects:
            filters:
              person:
                min_area: 1500
                max_area: 100000
                threshold: 0.75
                min_score: 0.60
          clips:
            enabled: True
            objects:
            - car
            - person
            - dog
            - cat
          snapshots:
            enabled: True
            timestamp: False
            retain:
              default: 14
        # --
        back:
          ffmpeg:
            inputs:
            - path: rtsp://admin:${CAM_BACK_PASS}@10.0.40.9:554/h264Preview_01_sub
              roles:
              - detect
            - path: rtsp://admin:${CAM_BACK_PASS}@10.0.40.9:554/h264Preview_01_main
              roles:
              - clips
              - record
              - rtmp
          height: 480
          width: 640
          fps: 7
          objects:
            filters:
              person:
                min_area: 1500
                max_area: 100000
                threshold: 0.75
                min_score: 0.60
          clips:
            enabled: True
            objects:
            - person
            - dog
            - cat
          snapshots:
            enabled: True
            timestamp: False
            retain:
              default: 14
    podAnnotations:
      configmap.reloader.stakater.com/reload: "frigate-config"
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
                - key: feature.node.kubernetes.io/custom-coral-tpu
                  operator: In
                  values:
                    - "true"
                - key: feature.node.kubernetes.io/custom-intel-gpu
                  operator: In
                  values:
                    - "true"
    resources:
      requests:
        gpu.intel.com/i915: 1
        memory: 100Mi
        cpu: 500m
      limits:
        gpu.intel.com/i915: 1
        memory: 2000Mi
