---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app readarr
  namespace: media
spec:
  interval: 15m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: kah-common-chart
      version: 1.1.2
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 15m
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    global:
      nameOverride: *app
    image:
      repository: lscr.io/linuxserver/readarr
      tag: nightly-version-0.1.1.1377
    env:
      TZ: "Europe/Warsaw"
    ingress:
      main:
        enabled: true
        ingressClassName: "traefik"
        annotations:
          cert-manager.io/cluster-issuer: "letsencrypt-production"
          hajimari.io/enable: "true"
          hajimari.io/icon: "book"
        hosts:
          - host: &host "readarr.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host
            secretName: readarr-tls
    podSecurityContext:
      supplementalGroups:
        - 65537
    persistence:
      config:
        enabled: true
        existingClaim: readarr-config-v1
      books:
        enabled: true
        existingClaim: nfs-media-books-pvc
        mountPath: /books
      downloads:
        enabled: true
        existingClaim: nfs-media-downloads-pvc
        mountPath: /downloads
      backup:
        enabled: true
        type: nfs
        server: ${NAS_ADDR}
        path: /volume2/Backups/apps/readarr
        mountPath: /config/Backups
        readOnly: false
