---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: hajimari
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://hajimari.io
      chart: hajimari
      version: 1.1.1
      sourceRef:
        kind: HelmRepository
        name: hajimari-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: ghcr.io/toboshii/hajimari
      tag: v0.1.0
    env:
      TZ: "Europe/Warsaw"
    hajimari:
      namespaceSelector:
        matchNames:
          - home-assistant
          - media
          - monitoring
      # customApps:
      #   - name: Mail
      #     url: "https://mail.${SECRET_DOMAIN}"
      #     icon: email
      groups:
        - name: Communicate
          links:
            - name: Discord
              url: "https://discord.com"
            - name: Gmail
              url: "https://gmail.com"
            - name: Slack
              url: "https://slack.com/signin"
        - name: Cloud
          links:
            - name: Box
              url: "https://box.com"
            - name: Dropbox
              url: "https://dropbox.com"
            - name: Drive
              url: "https://drive.google.com"
        - name: Dev
          links:
            - name: Codepen
              url: "https://codepen.io/"
            - name: Devdocs
              url: "https://devdocs.io"
            - name: Devhints
              url: "https://devhints.io"
        - name: Media
          links:
            - name: Spotify
              url: "http://browse.spotify.com"
            - name: Trakt
              url: "http://trakt.tv"
            - name: YouTube
              url: "https://youtube.com/feed/subscriptions"
        - name: Reading
          links:
            - name: Instapaper
              url: "https://www.instapaper.com/u"
            - name: Medium
              url: "http://medium.com"
            - name: Reddit
              url: "http://reddit.com"
        - name: Tech
          links:
            - name: Hacker News
              url: "https://news.ycombinator.com/"
            - name: The Verge
              url: "https://theverge.com/"
            - name: MIT Technology Review
              url: "https://www.technologyreview.com/"
    ingress:
      main:
        enabled: true
        annotations:
          kubernetes.io/ingress.class: "nginx"
        hosts:
          - host: "apps.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - "apps.${SECRET_DOMAIN}"
    persistence:
      data:
        enabled: true
        existingClaim: hajimari-config